# Generated by Django 4.2.8 on 2024-05-14 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tabitant_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bad",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bads",
                to="tabitant_api.post",
            ),
        ),
        migrations.AlterField(
            model_name="good",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goods",
                to="tabitant_api.post",
            ),
        ),
        migrations.AlterField(
            model_name="good",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="good",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="follow",
            unique_together={("follower", "followee")},
        ),
    ]
