# Generated by Django 5.0.4 on 2024-05-15 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabitant_api', '0002_alter_bad_post_alter_good_post_alter_good_user_and_more'),
        ('tabitant_api', '0003_alter_award_options_alter_bad_options_and_more'),
    ]

    operations = [
    ]
