# Generated by Django 5.0.4 on 2024-05-18 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabitant_api', '0005_alter_follow_unique_together_alter_award_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodcomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='tabitant_api.comment'),
        ),
        migrations.CreateModel(
            name='BadComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bads', to='tabitant_api.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'コメントへの Bad',
                'verbose_name_plural': 'コメントへの Bad',
            },
        ),
        migrations.AddConstraint(
            model_name='badcomment',
            constraint=models.UniqueConstraint(fields=('user', 'comment'), name='badcomment_unique'),
        ),
    ]
