# Generated by Django 5.0.4 on 2024-05-19 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabitant_api', '0007_alter_post_ml'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag_list',
            field=models.JSONField(default=list),
        ),
    ]
