# Generated by Django 5.0.4 on 2024-05-19 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabitant_api', '0007_auto_20240518_1904'),
        ('tabitant_api', '0008_alter_post_taglist'),
    ]

    operations = [
    ]
