# Generated by Django 5.0.4 on 2024-05-19 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabitant_api', '0009_merge_0007_auto_20240518_1904_0008_alter_post_taglist'),
    ]

    sql = """
        DROP VIEW IF EXISTS tabitant_api_user_emotion_view;
        CREATE VIEW tabitant_api_user_emotion_view AS 
        SELECT ROW_NUMBER() OVER() AS id,
               user.id AS user_id,
               AVG(post.emotion_ureshii) AS emotion_ureshii,
               AVG(post.emotion_omoshiroi) AS emotion_omoshiroi,
               AVG(post.emotion_samishii) AS emotion_samishii,
               AVG(post.emotion_shimijimi) AS emotion_shimijimi,
               AVG(post.emotion_odayaka) AS emotion_odayaka,
               AVG(post.emotion_ikari) AS emotion_ikari,
               SQRT(AVG(post.emotion_ureshii) * AVG(post.emotion_ureshii) + AVG(post.emotion_omoshiroi) * AVG(post.emotion_omoshiroi) + AVG(post.emotion_samishii) * AVG(post.emotion_samishii) + 
               AVG(post.emotion_shimijimi) * AVG(post.emotion_shimijimi) + AVG(post.emotion_odayaka) * AVG(post.emotion_odayaka) + AVG(post.emotion_ikari) * AVG(post.emotion_ikari)) AS norm2
        FROM tabitant_api_user AS user
        LEFT OUTER JOIN tabitant_api_post AS post
        ON user.id = post.user_id
        GROUP BY user.id;
    """

    reverse_sql = """
        DROP VIEW IF EXISTS tabitant_api_user_emotion_view;
    """

    operations = [
        migrations.RunSQL(sql, reverse_sql)
    ]

