# Generated by Django 5.0.4 on 2024-05-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabitant_api', '0010_auto_20240519_1838'),
    ]

    sql = """
        CREATE VIEW tabitant_api_user_emotion_view AS 
        SELECT ROW_NUMBER() OVER() AS id,
               user.id AS user_id,
               AVG(post.emotion_ureshii) AS emotion_ureshii,
               AVG(post.emotion_omoshiroi) AS emotion_omoshiroi,
               AVG(post.emotion_samishii) AS emotion_samishii,
               AVG(post.emotion_shimijimi) AS emotion_shimijimi,
               AVG(post.emotion_odayaka) AS emotion_odayaka,
               AVG(post.emotion_ikari) AS emotion_ikari,
               SQRT(AVG(post.emotion_ureshii) * AVG(post.emotion_ureshii) + AVG(post.emotion_omoshiroi) * AVG(post.emotion_omoshiroi) + AVG(post.emotion_samishii) * AVG(post.emotion_samishii) + 
               AVG(post.emotion_shimijimi) * AVG(post.emotion_shimijimi) + AVG(post.emotion_odayaka) * AVG(post.emotion_odayaka) + AVG(post.emotion_ikari) * AVG(post.emotion_ikari)) AS norm2
        FROM tabitant_api_user AS user
        LEFT OUTER JOIN tabitant_api_post AS post
        ON user.id = post.user_id
        GROUP BY user.id;
    """

    reverse_sql = """
        DROP VIEW IF EXISTS tabitant_api_user_emotion_view;
    """

    operations = [
        migrations.RunSQL(reverse_sql, sql),
        migrations.CreateModel(
            name='UserEmotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion_ureshii', models.FloatField()),
                ('emotion_omoshiroi', models.FloatField()),
                ('emotion_odayaka', models.FloatField()),
                ('emotion_shimijimi', models.FloatField()),
                ('emotion_samishii', models.FloatField()),
                ('emotion_ikari', models.FloatField()),
                ('norm2', models.FloatField()),
            ],
            options={
                'db_table': 'tabitant_api_user_emotion_view',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='detailed_place',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.RunSQL(sql, reverse_sql)
    ]
