# -*- coding: utf-8 -*-
"""UTAKAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jo4ALcboU8bTduJlQDXaBZICscPp00tg
"""

# !pip install transformers datasets evaluate accelerate torch fugashi ipadic

import json

with open("tanka.json", encoding="utf8") as f:
  data = json.load(f)

for item in data:
  for key in item['emotion']:
    # item['emotion'][key] = int((item['emotion'][key] - 1) // 2)
    item['emotion'][key] = \
      0 if item['emotion'][key] <= 3 else \
      1 if item['emotion'][key] <= 6 else 2

from datasets import Dataset

to_learn = ["emotion", "tag"]

label_names = []
for i in to_learn:
    for j in data[0][i]:
        label = i + "." + j
        label_names.append(label)
print(f'label order: {label_names}')

label_list_of_name = {x: set() for x in label_names}
for item in data:
  for i in to_learn:
    for j in item[i]:
      label_list_of_name[i + "." + j].add(item[i][j])
is_binary = {}
for name in label_list_of_name:
    is_binary[name] = (len(label_list_of_name[name]) <= 2)

new_data = { "text": [], "label": [] }
for item in data:
  new_data["text"].append(item["content"])
  labels = []
  for i in to_learn:
    for j in item[i]:
      name = i + "." + j
      if is_binary[name]:
        if item[i][j] == 0: continue
      else:
        name += "." + str(item[i][j])
      labels.append(name)
  new_data["label"].append(labels)

label_list = []
for name in label_names:
  if is_binary[name]:
    label_list.append(name)
  else:
    for i in sorted(label_list_of_name[name]):
        label_list.append(name + "." + str(i))

dataset_raw = Dataset.from_dict(new_data)
print(f'label_list: {label_list}')

from transformers import TrainingArguments

import transformers
from transformers import (
    AutoConfig,
    AutoModelForSequenceClassification,
    AutoTokenizer,
    DataCollatorWithPadding,
    EvalPrediction,
    HfArgumentParser,
    Trainer,
    TrainingArguments,
    default_data_collator,
    set_seed,
)

model_name = "train-3/checkpoint-19288"

# Load pretrained model and tokenizer
# In distributed training, the .from_pretrained methods guarantee that only one local process can concurrently
# download model & vocab.
config = AutoConfig.from_pretrained(
    model_name,
    num_labels=len(label_list),
    finetuning_task="text-classification",
    problem_type = "multi_label_classification",
)

tokenizer = AutoTokenizer.from_pretrained(
    model_name,
)
model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    config=config,
)

label_to_id = {v: i for i, v in enumerate(label_list)}
model.config.label2id = label_to_id
model.config.id2label = {id: label for label, id in label_to_id.items()}

# model.push_to_hub("y-aut/utakai-emotion-tag")
tokenizer.push_to_hub("y-aut/utakai-emotion-tag")
